"""@Author: Ganapathy Raman Madanagopal
   File description: Words that occur commonly in spam amil as listed here """

import re

blackPhrases = [

#A 
'accept credit cards',
'account details',
'acne',
'act now!',
'active stock',
'additional income',
'adipex',
'adipren',
'adult',
'advertisement',
'advertising',
'advicer',
'affordable',
'allergies',
'amazing new discovery',
'ambien',
'as seen on tv',
'asthma',
'auto-generated',
'auto loan',
'auto loans',

#B 
'baccarrat',
'bachelor',
'bad credit',
'bank transfer',
'beat stress',
'be your own boss',
'big dick',
'blogspot',
'bllogspot',
'booker',
'botox',
'bulgary',
'burn fat',
'business investment',
'business offer',
'business proposal',
'buy direct',
'buy now',
'buying judgments',
'buy online',

#C 
'call anywhere',
'came up a winner',
'cancel at anytime',
'career opportunity',
'career singles',
'carisoprodol',
'cashcashcash',
'casino',
'casinos',
'chatroom',
'cheap',
'cheapest pills',
'cialis',
'clearance',
'click here',
'click to play',
'click to win',
'credit',
'credit card',
'cwas',
'cyclen',
'cyclobenzaprine',

#D 
'dating',
'day-trading',
'debt free',
'degree program',
'depression',
'dick',
'dig up dirt on friends',
'diploma',
'diplomas',
'discount',
'discreet meeting',
'discreet meetings',
'discreet ordering',
'doctor approved',
'doctor prescribed',
'double your',
'double your money',

#E 
'earn a college degree',
'earn a degree',
'earn big',
'earn extra money',
'earn extra cash',
'earning potential',
'easy money',
'ejaculation',
'eliminate your debt',
'email database',
'enlargement',
'elkedeseen',
'erection',
'erections',
'escorts',
'explicit',
'extra income',

#F
'fast cash', 
'fast delivery',
'financial freedom',
'find someone special',
'find your match',
'fioricet',
'fire your boss',
'foreign accounts',
'fountain of youth',
'free cell phone',
'free degree',
'free diploma',
'free game',
'free games',
'free gas',
'free gift',
'free list',
'free listing',
'free minutes',
'free money',
'free of debt',
'free offer',
'free phone',
'free reading',
'free readings',
'free screen savers',
'free screensavers',
'freenet-shopping',
'fuck',
'future mailing',
'further mailing',

#G 
'get out of debt',
'get results',
'get results now',
'get rich quick',
'get your reading',
'great offer',
'great discounts',

#H 
'health products',
'heartburn',
'higher income',
'home based',
'home employment',
'home owner',
'home workers',
'homeworkers',
'horny',
'hot deals',
'hot stocks',
'housewife',
'housewives',
'huge dick'
'hydrocodone',

#I 
'improve your size',
'incest',
'income from home',
'insurance',
'investment',
'investor',
'ionamin',

#J 
'job search',
'join millions',
'join now',
'just released',

#K 

#L 
'levitra',
'limted offer',
'limted time offer',
'lottery',
'lotto games',
'loose weight',
'lose weight',
'low interest',
'low interest rate',
'low interest rates',
'low price',
'low prices',
'lowest price',

#M 
'macinstruct',
'mail list',
'mailing list',
'make a living',
'make money',
'make maoney fast',
'make money at home',
'make $',
'marketing',
'mastercard',
'matchmaker',
'matchmaking',
'medication',
'medications',
'meds',
'meet new singles',
'meet singles',
'meet someone special',
'meridia',
'million dollars',
'millions of dollars',
'mlm',
'money making',
'money back guarantee',
'more income',
'morgage',
'mortgage',
'muscle relaxants',

#N 
'natural weight loss',
'new product',
'no hidden costs',
'no age restrictions',
'no medical exams',
'no purchase necessary',
'no questions asked',

#O 
'oem',
'oem software',
'omega',
'-online',
'online gambling',
'online-gambling',
'online pharmacy',
'orgasm',

#P 
'pain relief',
'passwords',
'paxil',
'penis',
'personals',
'pharmacy',
'pharmaceuticals',
'phendimetrazine',
'phentamine',
'phentermine',
'pheramones',
'pherimones',
'photos of singles',
'please read',
'platinum-celebs',
'poker-chip',
'porno',
'poze',
'premature',
'prescription',
'privacy assured',
'product for less',
'products for less',
'protect yourself',
'psychic',
'pussy',

#Q 
'quit smoking',
'quit your job',

#R
'red light camera',
'refinance',
'recover your losses',
'risk free',
'rock hard',
'rolex',

#S 
'sale',
'satisfaction guaranteed',
'save',
'score with babes',
'scratch and win',
'scratch off',
'scratch-off',
'searching engine listings',
'searching for you',
'sell now',
'serious cash',
'sex',
'sexual health',
'sign up',
'sign up now',
'signup',
'sleeping disorders',
'slot-machine',
'slut',
'sluts',
'soma',
'special promotion',
'speed cameras',
'spyware',
'src=3D"cid:',
'src="cid:',
'stcok dividend',
'stock quotes',
'stock update',
'stop paying',
'substantial income',
'super deal',
'super deals',

#T 
'taboo',
'take a survey',
'take surveys'
'tarot',
'teen',
'teenage',
'teens',
'tenuate',
'traders report',
'tramadol',
'trim-spa',
'triple-x',
'tripple x',
'tripplex',

#U 
'ultram',
'ultmost confidentiality',
'utmost confidentiality',
'university diploma',
'urgent',

#V 
'valium',
'venture capitol',
'viagara',
'viagra',
'vicodin',
'vioxx',
'visit our website',

#W 
'want a watch',
'web cam',
'web traffic',
'weight reduction',
'wholesale',
'win now',
'winner confirmation',
'winning number',
'work at home',
'worry free',
'worry-free',

#X
'xanax',
'x rated',
'x x x',
'xanax',
'xenical',
'xp professional',
'x-rated',
'xxx',

#Y 
'you have won',
'you won',
'you are a winner',
'you\'re a winner',

#Z 
'zero percent',
'zolus'

#[0-9]
'3 inches',
]

blackRegExps = [re.compile(r'font-size:\s*[01][^0-9\.]',re.I), # tiny html font
                re.compile(r'[a-z]<!.*?>[a-z]',re.I), # html comments in middle of a word
                re.compile(r'http://[0-9]+\.[0-9]+\.[0-9]+\.',re.I), # numerical url
                re.compile(r'pills[0-9]*\.gif',re.I)]
